!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      pitch: -0.03
      roll: 0.04
      state: true
      type: ''
      x: 0.94
      y: 0.6
      yaw: 0.62
      z: -0.7
    state: []
  pitch: -0.03
  roll: 0.04
  x: 0.94
  y: 0.6
  yaw: 0.62
  z: -0.7
state: []