# Old Extrinsics
float64[3] translation
float64[3] euler_angles

# Matchings
geometry_msgs/Point[] obsCentroids
geometry_msgs/Point[] bbsCentroids

---
# New Extrinsics
float64[3] translation
float64[3] euler_angles