!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      pitch_left: -0.3769911184307752
      pitch_right: -0.042635106542868326
      roll_left: 0.0
      roll_right: 0.04908282358659542
      state: true
      type: ''
      x_left: 0.6
      x_right: 2.1974776
      y_left: 0.21056701
      y_right: -0.08864819
      yaw_left: 2.4504422698000385
      yaw_right: 0.6364464859870094
      z_left: -0.06
      z_right: -0.760316
    state: []
  pitch_left: -0.3769911184307752
  pitch_right: -0.042635106542868326
  roll_left: 0.0
  roll_right: 0.04908282358659542
  x_left: 0.6
  x_right: 2.1974776
  y_left: 0.21056701
  y_right: -0.08864819
  yaw_left: 2.4504422698000385
  yaw_right: 0.6364464859870094
  z_left: -0.06
  z_right: -0.760316
state: []
